export const SONG_LIB = [
  {
    _id: 1,
    name: "Again",
    path: "./music/Fullmetal-Alchemist-Brotherhood-Again.mp3",
    image: "./images/Fullmetal-Alchemist.jpg",
    singer: "FAB",
    album: "Fullmetal Alchemist Brotherhood",
    duration: "1:29",
    primaryBackgroundTint: "#ed213a",
    secondaryBackgroundTint: "#f14747",
  },
  {
    _id: 2,
    name: "Gurenge",
    path: "./music/Demon-Slayer-Gurenge-Male.mp3",
    image: "./images/Demon-Slayer.jpg",
    singer: "Lisa",
    album: "Demon Slayer",
    duration: "1:29",
    primaryBackgroundTint: "#16c3f7",
    secondaryBackgroundTint: "#adc0c5",
  },
  {
    _id: 3,
    name: "My Hero Academia",
    path: "./music/My-Hero-Academia.mp3",
    image: "./images/My-Hero-Academia.jpg",
    singer: "My Hero Academia",
    album: "My Hero Academia",
    duration: "1:29",
    primaryBackgroundTint: "#f7f316",
    secondaryBackgroundTint: "#9e9c33",
  },
  {
    _id: 4,
    name: "Haikyu",
    path: "./music/Haikyu-Spyair.mp3",
    image: "./images/Haikyu.jpg",
    singer: "Spyair",
    album: "Haikyu",
    duration: "2:59",
    primaryBackgroundTint: "#fe8c00",
    secondaryBackgroundTint: "#f83600",
  },
];
